#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

FORBIDDEN_HTTPS_URL="https://github.com/musbi-projects/musbi-fe.git" # insert your remote url (https)
FORBIDDEN_SSH_URL="git@github.com:musbi-projects/musbi-fe.git" # insert your remote url (ssh)
FORBIDDEN_REF="refs/heads/main" # insert branch ref​

remote_ref=${1} # push 하려는 브랜치
url=${2} # 원격 저장소 

echo $remote
echo $url

if [ "$url" != "$FORBIDDEN_HTTPS_URL" -a "$url" != "$FORBIDDEN_SSH_URL" ]
then
    exit 0 # Forked Project 에서는 제한하지 않음
fi
if [ "$remote_ref" == "$FORBIDDEN_REF" ]
then
    echo "DO NOT PUSH it master"
    exit 1 # 금지된 ref 로 push 를 실행하면 에러
fi
exit 0